import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import NavBar from '../components/navbar'
import SideBar from '../components/sidebar'
import Workspace from '../components/workspace'
import dynamic from 'next/dynamic'

// const Workspace = dynamic(() => import('../components/workspace'), {
//   ssr: false,
//   });

const Home: NextPage = () => {
  return (
    <div className="content">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar/>

      <main className="main">
        <Workspace/>
      </main>

    </div>
  )
}

export default Home
